### ISSUE TITLE
[Bug]: Deprecation notice due to inheritance validation

### ISSUE THREAD

**Issue by luislard** [inpsyde/wp-app-container#13]
### Description of the bug

I am checking if we can move one of our projects to PHP8.1 and I am getting a deprecation notice in wp-app-container see:
```
Deprecated: Return type of Inpsyde\App\EnvConfig::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/public/wp-content/mu-plugins/unilux-app-container/vendor/inpsyde/wp-app-container/src/EnvConfig.php on line 257
```

This error is documented in [Backward Incompatible Changes](https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.core.type-compatibility-internal)

I tried to change the return type but it will fail in PHP7.* because the [mixed return type was introduced in PHP8](https://php.watch/versions/8.0/mixed-type)

As I can see we are trying to support PHP7 in the v3.x of this package -> [inferred because of this](https://github.com/inpsyde/wp-app-container/blob/3.x/.github/workflows/qa.yml#L44)

So we have 3 options:
Create a new major v4 that only supports PHP >= 8.0
Stay in v3 but add the #[\ReturnTypeWillChange] to the method (easiest)
Ignore the deprecation

### Reproduction instructions

Use v3 of this package with PHP8.1

### Expected behavior

Remove the deprecation notice

### Environment info

ddev with PHP8.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luislard** [comment]
I am trying to replicate the issue with Psalm, it seems that psalm has suppressed the error from happening:
They have it documented in [here](https://psalm.dev/docs/running_psalm/issues/MethodSignatureMustProvideReturnType/), but they are removing it from the tests run? see [here](https://github.com/vimeo/psalm/blob/eeb12bc285b3ebfeac7f6f8328a2917a2b0a1225/tests/DocumentationTest.php#L287-L289)

Now will try to replicate the issue with PHPUnit, will let you know later

**Comment by luislard** [comment]
Tried to trigger the issue in PHPUnit.

I checked what happens if I remove the attribute in any of the files by PHPUnit itself and the PHPUnit suite didn't catch the error. [See my test](https://github.com/luislard/phpunit/actions/runs/3218493560)

I will just add the attribute in the required places.

**Comment by gmazzap** [comment]
PR merged.
